---
- name: Ensure URL prefix is present in Jenkins config.
  lineinfile:
    dest: "{{ jenkins_init_file }}"
    insertafter: '^JENKINS_ARGS='
    regexp: '^JENKINS_ARGS\+=" --prefix='
    line: 'JENKINS_ARGS+=" --prefix={{ jenkins_url_prefix }}"'
    state: present
  register: jenkins_init_prefix

- name: Immediately restart Jenkins on init config changes.
  service: name=jenkins state=restarted
  when: jenkins_init_prefix.changed

- name: Set HTTP port in Jenkins config.
  lineinfile:
    backrefs: yes
    dest: "{{ jenkins_init_file }}"
    regexp: '^{{ jenkins_http_port_param }}='
    line: '{{ jenkins_http_port_param }}={{ jenkins_http_port }}'
  register: jenkins_http_config

- name: Immediately restart Jenkins on http config changes.
  service: name=jenkins state=restarted
  when: jenkins_http_config.changed

- name: Fix issue with csrf param in Jenkins config.
  lineinfile:
    backrefs: yes
    dest: "{{ jenkins_init_file }}"
    regexp: '^JENKINS_JAVA_OPTIONS='
    line: 'JENKINS_JAVA_OPTIONS="-Djava.awt.headless=true -Dhudson.security.csrf.requestfield=Jenkins-Crumb"'
  register: jenkins_fix_config

- name: Immediately restart Jenkins on http config changes.
  service: name=jenkins state=restarted
  when: jenkins_fix_config.changed
